services:
  backend:
    build: ./backend
    # ▼▼▼ この command の一行を追加します ▼▼▼
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app