services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1g
    # ▼▼▼ この environment セクションを追加 ▼▼▼
    environment:
      - HOST_PROJECT_PATH=${PWD}/backend
    # ▲▲▲ ここまで ▲▲▲