version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude /tmp
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock # サンドボックス実行用
    mem_limit: 1g

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend

  refix-ts-runner:
    image: refix-ts-runner
    build:
      context: ./backend
      dockerfile: Dockerfile.typescript-sandbox

  refix-sandbox-runner:
    image: refix-sandbox-runner
    build:
      context: ./backend
      dockerfile: Dockerfile.sandbox