services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude /tmp
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1g

  # ▼▼▼ 以下の2つのサービス定義を追加 ▼▼▼
  refix-ts-runner:
    image: refix-ts-runner
    build:
      context: ./backend
      dockerfile: Dockerfile.typescript-sandbox

  refix-sandbox-runner:
    image: refix-sandbox-runner
    build:
      context: ./backend
      dockerfile: Dockerfile.sandbox
  # ▲▲▲ ここまで追加 ▲▲▲