# Node.jsの公式イメージをベースにする
FROM node:20-bookworm

# 作業ディレクトリを作成・設定
WORKDIR /app

# まずは設定ファイルとpackage.jsonだけをコピー
COPY ts-sandbox-files/package.json ./
COPY ts-sandbox-files/jest.config.js ./
COPY ts-sandbox-files/tsconfig.json ./

# npm install を実行して、node_modulesをイメージ内に作成
RUN npm install